# Basic section
home: "/home"
redirectTimeOut: 10
private: false
# END #

# Header section
hasHeader: true
# It can either h or display
headerType: display
# header size can be given (1 - 6) (1 is the biggest, 6 is the smallest in case headerType is display otherwise it reversed)
headerSize: 5
# END #

# Contact section
contactUs: { ownerName: "Balogh Zoltán Sándor",supportEmail: "zoltan.balogh@avolantis.net" }
# END #
